### ISSUE TITLE
IRC Colour and beep support

### ISSUE THREAD

**Issue by Fuchs** [xnrand/SimpleIRCBridge#1]
Yes, hello, this is fox. 

I liek you mod, but it needs to support 1 IRC coluors and bieb. 

Thankx!

**Comment by xnrand** [comment]
Could be useful: [existing IRC-Minecraft color mapping](https://github.com/xnrand/saraswati-bungee/blob/patch-away-from-pircbot/src/main/java/com/michealharker/saraswati/irc/SaraswatiIRC.java#L197)

**Comment by Fuchs** [comment]
bah, I was hoping for a similarly silly response. 
I'll look into it next week, I assume the build environment for it will take more time than actually writing it :p
